### ISSUE TITLE
Can`t build - status is not pending - After Build error

### ISSUE THREAD

**Issue by BrunoJunior** [corpsee/php-censor#68]
I had some errors in my build.
It's tagged as finished.
But new messages come in build log and I have some running psocesses :
![image](https://cloud.githubusercontent.com/assets/4368255/26196861/9236f26e-3bc0-11e7-831e-b14ed3f00ddb.png)
![image](https://cloud.githubusercontent.com/assets/4368255/26196872/a06bacc6-3bc0-11e7-92f9-a9a20c5830d9.png)
There is my project conf :
![image](https://cloud.githubusercontent.com/assets/4368255/26196921/c3b13296-3bc0-11e7-8594-6befaa165359.png)
And the php-censor yml file :
```
build_settings:
  clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
  ignore:
    - "vendor"

setup:
  composer:
    action: "install"
  shell:
    - "mkdir %BUILD_PATH%/instance"
    - "cp %BUILD_PATH%/build_tools/config_instance.php %BUILD_PATH%/instance/config_instance.php"

test:
  php_parallel_lint:
    ignore:
      - "vendor"
      - "test"
    extensions: php
  php_loc:
    directory: "app"
  php_code_sniffer:
    path: "fwk"
  atoum:
```

**Comment by corpsee** [comment]
I guess problem in string `atoum` without arguments (I've already seen this behavior of worker). I will try to test and fix worker's config parsing problem. Thanks.

**Comment by corpsee** [comment]
@BrunoJunior Can you re-run build with debug and post build log?

**Comment by corpsee** [comment]
I fixed this behavior in branch `bugfix-issue-68`. @BrunoJunior Can you test it?

**Comment by BrunoJunior** [comment]
I can't test ...
Fatal error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /vagrant/php-censor/src/B8Framework/Database.php on line 88
Maybe the same problem than issue #73

**Comment by corpsee** [comment]
Hmm... I rebased `bugfix-issue-68` branch on #73 about 1 hour ago. @BrunoJunior Try to delete local `bugfix-issue-68` branch and checkout it again please.

**Comment by BrunoJunior** [comment]
Weird ... I didn't make a local branch, only checkout remote one ... It didn't work
I made git checkout --track ... And I don't have the MYSQL error anymore
I'll test to re-run a build

**Comment by BrunoJunior** [comment]
The leak seems to be fix but I still have a lot of `Can`t build - status is not pending` in Build logs tab.
![image](https://cloud.githubusercontent.com/assets/4368255/26554626/6c42c932-4491-11e7-9114-519a9971e037.png)

**Comment by corpsee** [comment]
@BrunoJunior Any exceptions or errors in the build log before 'PLUGIN: FAILED'? What plugin is failed? Perhaps Have you any another details? I'm trying to reproduce your situation. Thanks.

**Comment by StudioMaX** [comment]
I also had this error. Please check that:
- Your server has enough free space. git clone, vendors, some cache files from plugins could take a lot of space at the setup stage
- Personally I found that PhpCsFixer was configured incorrectly, which caused the CPU was loaded to 100%, and after a while the php process was killed by the OS.

**Comment by corpsee** [comment]
I reproduced this behavior (Multiple "Can\`t build - status is not pending" messages after hard fail). And after my fixes behavior doen't reproduce.
I merge fixes fo `master` branch and close this issue. Feel free to reopen if problem appear again.
